language_mapping = {
    "C": "C",
    "c": "C",
    "C++": "C++",
    "cpp": "C++",
    "c++": "C++",
    "H": "H",
    "h": "H",
    "Java": "Java",
    "java": "Java",
    "jdk": "Java",
    "Jar": "Jar",
    "jar": "Jar",
    "lib": "Jar",
    "Android APK": "Android APK",
    "adnroid_apk": "android_apk",
    "apk": "Android APK",
    "sdk": "Android APK",
    "JavaScript": "JavaScript",
    "javascript": "JavaScript",
    "JS": "JavaScript",
    "js": "JavaScript",
    "TypeScript": "TypeScript",
    "typescript": "TypeScript",
    "TS": "TypeScript",
    "ts": "TypeScript",
    "Python": "Python",
    "python": "Python",
    "PY": "Python",
    "py": "Python",
    "PHP": "PHP",
    "php": "PHP"
}
